### ISSUE TITLE
Support retrying failed examples by default

### ISSUE THREAD

**Issue by bootstraponline** [titusfortner/saucer#5]
https://github.com/NoRedInk/rspec-retry worked last time I looked into Sauce retry best practices.

**Comment by titusfortner** [comment]
I think this is outside the scope for this project. The intention isn't to wrap all rspec config. If the gem gets in the way of your adding it, that's a different story.

**Comment by bootstraponline** [comment]
Anyone doing testing at scale will need to support retry. This sounds like not much is changing in terms of expecting users to build out something reliable on their own.

**Comment by titusfortner** [comment]
Yes, this project is focused on making it easier to run your tests with Sauce, with the goal that the ideas can be applied to other bindings.

Also, as a side note, I actually disagree on the need to support retries, and I have specifically avoided it at previous companies. Something like this RetryingClient might be more acceptable: https://github.com/watir/watir/pull/469#issuecomment-270056732

**Comment by bootstraponline** [comment]
> I actually disagree on the need to support retries,

I think you should chat with customers then. Retries are the only way to achieve stability at scale. This isn't even limited to WebDriver testing. 

The watir link looks like moving retries to the individual http request level which is valuable but won't help with RSpec expectation failures. When I worked on angular automation, we did both (http level retry + RSpec level retry).

- https://github.com/bootstraponline/angular_automation

It sounds like this is going to miss the mark in terms of solving the real needs. For any language, there common features I've seen include:

- Per method parallel execution
- Sauce job status reporting
- Sauce Jenkins plugin integration
- Test retry
- JUnit XML reports

At least sauce_ruby attempted to solve these problems. I was hoping we'd identify a happy path set of tech (Jenkins/RSpec/Sauce) and then provide a solution that is "batteries included" for most use cases. Then that'd be easy to replicate across languages.

**Comment by titusfortner** [comment]
I'm saying *I've written test suites that worked just fine without retries. ymmv.

Regardless, this is still out of scope for interacting with Sauce. There's a reason we're not still supporting `sauce_ruby`, it tried to do way too many things. Good libraries focus on doing one thing well rather than trying to hack together something that does all the things. There is so much possible test code that this isn't going to include (pretty much see everything in the `watir_install` gem for test data management and page objects, etc). Actually, it might make sense to add `rspec-retry` to that gem. This gem just has to not get in the way of you doing the other things you want to do. 

The focus is exclusively making it easier for our clients to interact with Sauce, and gather data that will make it easier for us to serve their needs. The rest of your suggestions (thank you for providing them) are more likely to get attention. This is still a work in progress. We're going to meet after SauceCon to prioritize things and figure out how to expand this prototype to other languages.

**Comment by bootstraponline** [comment]
> The focus is exclusively making it easier for our clients to interact with Sauce

clients on Sauce are going to fail if they don't follow these well understood best practices. It's easier for clients if the basic needs are met instead of making them figure it out on their own. Dropping retry support is just generating additional work.

I think relying on personal experience for this is not the right way to design software. You'd need an actual user with a large test suite to validate the workflow. How many clients with 1k+ WebDriver tests don't use retry?

**Comment by titusfortner** [comment]
> clients on Sauce are going to fail if they don't follow these well understood best practices
1. Retries are definitely *not* best practice. If you need them, you are doing something else wrong.
2. Page Objects are definitely best practice, but we're not incorporating them in this gem because it is outside of the scope.
3. It is easy to add retries if you decide you need them. Apparently all of the clients with 1k+ tests already have figured it out.

**Comment by bootstraponline** [comment]
> Retries are definitely not best practice.

uh, what? I think there's not a single client doing WebDriver testing at scale (1k+) who doesn't retry.

**Comment by bootstraponline** [comment]
If Sauce has figured out some magic way to get 100% stability without retry... then please share it with the world. 😄

**Comment by titusfortner** [comment]
https://www.youtube.com/watch?v=yo3uxqwTxk0

**Comment by titusfortner** [comment]
A lot of it has to do with starting a project with good test design practices, which, yeah, most companies don't do. But using retries is a hack / workaround to bad tests. You can't consider a bandaid a best practice regardless of how many people use it.

**Comment by bootstraponline** [comment]
> Best Practice: Have a Retry Strategy for Handling Flakes
> https://wiki.saucelabs.com/display/DOCS/Best+Practice%3A+Have+a+Retry+Strategy+for+Handling+Flakes

At this point, the project isn't even following Sauce Lab's own best practices. Which is unfortunate because it's not going to add value to customers who need this tech but lack the internal teams to build custom solutions.

**Comment by titusfortner** [comment]
That article isn't saying to just retry and ignore (like rspec-retry does). It is arguing for logging intermittent errors and tracking them so you can fix them. As far as I know there isn't an easy option for doing that. And building *that is definitely more resources than we have to devote at this time. :)

**Comment by bootstraponline** [comment]
>  If they continue to fail after a second or third retry, chances are that the issue is with the functionality you're testing, rather than the test itself.

^ is what rspec-retry does. It reduces the noise so that the actual errors bubble up.

I agree that retry and ignore isn't ideal. Logging errors is a better approach but few companies have resources to do that.

In a typical workflow of requiring WebDriver tests to pass on pull request merges, retries are required even for small test suites. Otherwise failures due to underlying flakiness in the automation framework will waste everyones time.
